name: github pages

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: clean
      run: rm -rf node_modules package-lock.json

    - name: install
      run: npm install

    - name: build
      run: npm run build-storybook
      env:
        URL_PREFIX: react-minolith

    - name: add nojekyll
      run: touch ./storybook-static/.nojekyll

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./storybook-static
