name: github pages

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: install, build and deploy
      uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
      env:
        URL_PREFIX: react-minolith
        NODE_OPTIONS: --max-old-space-size=8192
      with:
        install_command: npm install
        build_command: npm run build-storybook
        path: storybook-static
        checkout: false
